### ISSUE TITLE
"tasks:" option with an empty array runs my default task

### ISSUE THREAD

**Issue by mhchen** [JacksonGariety/gulp-nodemon#100]
Using this gulpfile.js:

```
var gulp = require('gulp');
var nodemon = require('gulp-nodemon');

gulp.task('serve', function(cb) {
  var started = false;
  nodemon({
    script: './bin/www',
    ext: 'js jade',
    ignore: [
      'sass/**',
      'public/**',
      'gulpfile.js'
    ],
    tasks: []
  });
});

gulp.task('default', function() {
  console.log('running default task');
});
```

If I run 
```
$ gulp serve
```

then update one of my .jade files, it runs my default task. Console output:

```
[19:35:03] Using gulpfile ~/projects/nodemontest/gulpfile.js
[19:35:03] Starting 'serve'...
[19:35:03] [nodemon] 1.8.1
[19:35:03] [nodemon] to restart at any time, enter `rs`
[19:35:03] [nodemon] watching: *.*
[19:35:03] [nodemon] starting `node ./bin/www`
[19:35:06] Using gulpfile ~/projects/nodemontest/gulpfile.js
[19:35:06] Starting 'default'...
running default task
[19:35:06] Finished 'default' after 105 μs
[19:35:06] [nodemon] restarting due to changes...
[19:35:06] [nodemon] starting `node ./bin/www`
```

so it seems that the "tasks:"  option runs the default task if fed an empty array. I verified that this also happens when tasks: is a function that returns an empty array. I expect it to do nothing if given an empty tasks: array. 

Use case is I want to do something like the example where tasks are conditionally run based on what files have changed. For now this is working if I create a 'noop' gulp task that does nothing and insert that into the tasks array by default. I can look into a fix if someone can confirm that this is a legitimate issue. Otherwise let me know if I've misunderstood this option.

**Comment by damiandennis** [comment]
same issue here, respawns a new instance like in issue https://github.com/JacksonGariety/gulp-nodemon/issues/66 workaround is just to add a empty string as a task.

**Comment by mhchen** [comment]
Oh, looks like this was fixed in https://github.com/JacksonGariety/gulp-nodemon/commit/9e68c18fc3171f437adf43b30c35ebe70053c974. Just needs to make it into a release

**Comment by JacksonGariety** [comment]
@mhchen @damiandennis fixed
