### ISSUE TITLE
gulp-nodemon goes in a loop

### ISSUE THREAD

**Issue by subzworld** [JacksonGariety/gulp-nodemon#104]
Hi,
I've created a custom task in gulp that uses gulp-nodemon, however when I run the task and make any changes to my js file, the custom task goes in  a loop and keeps on calling the 'restart' event. 
The script I have used is pasted below:

`gulp.task('test',function(){
    nodemon({
        script:'js/main.js',
        ext:'js',
        ignore:['./node_modules/**'],
        env:{
            PORT:config.data.webserver.port
        },
        tasks: ['lint','sass','scripts']
    }).on('restart',function(){
        console.log("Restarted Myself");
    });
});`

**Comment by JacksonGariety** [comment]
The code you have looks fine to me.

Do the `lint`, `sass`, or `scripts` tasks call `test` by any chance? That would be an obvious one.

Otherwise you'll just have to take steps to debug:  Maybe try removing the `.on('restart')` event? Try removing the tasks altogether? Remove `env:`? Etc.

**Comment by subzworld** [comment]
The tasks (lint, scripts etc) mentioned in task do not call test. I'll try removing the on 'restart' etc to debug and would let you know.

Thanks,
Subroto 




On Mon, Feb 8, 2016 at 1:58 PM -0800, "G͔̟̭̈̃ͫͣͧ̿ͪ̈̂̊͆ͬͫͪ̊͠a̵̳͇̠̥̬̣̹̥̦̳̅ͩ͂̐ͤ̂ͨ͌r̳̦̗͖͓̥̼͙̭̩͍̹̫ͦ̍̾ͯ͒͘í͔͕̳͙̙ͨ͒́̑͐̆ͯ̑̌̍ͯ̈̐͜e̸͉͍͖̮̩̰͈̠̒ͦ̎͋ͮ̍ͭͬͬͤt̝͙͖̪͎̙̫̯̜̲̙̯͍͔ͣ̓̀ͯ͡y̳̜͖̭ͮ͛͗͗ͨ̊̈͒̉͊͐̈ͬ͛͟x̨͍̦̖̞̣͔ͮ̎̆̎͆̋̒ͧ͗͆ͤͣx̸̭̎̐ͨ̈ͯͯ͆͋̈̍ͧ̑ͭ́ͤͫͥx̼͕͎̪͈͙̉̿͗̈̂ͫ̉͑̂̒̅̆́" <notifications@github.com> wrote:












The code you have looks fine to me.



Do the lint, sass, or scripts tasks call test by any chance? That would be an obvious one.



Otherwise you'll just have to take steps to debug:  Maybe try removing the .on('restart') event? Try removing the tasks altogether? Remove env:? Etc.
