### ISSUE TITLE
gulp-nodemon watch w/ tasks doesn't seem to work

### ISSUE THREAD

**Issue by RavenHursT** [JacksonGariety/gulp-nodemon#105]
I have the following task that I'm trying to use for development. I have two other tasks than I need run before `gulp-nodemon` starts and restarts my server process.

It STARTS just fine, but upon discovering a change in my /src file tree, the two tasks are run, but the node process never restarts and I never see my .on('restart') message fire. It then just hangs after the two other tasks complete (I get Gulp "Finished..." messages for both of them). Am I missing something here?

```
import gulp from 'gulp'
import nodemon from 'gulp-nodemon'

gulp('watch', ['copy-assets', 'transpile'], () => {
  return nodemon({
    execMap: {
      js: `node`
    },
    script: `build/index.js`,
    watch: `src/**/*.js,
    ext: `js`,
    tasks: ['copy-assets', 'transpile']
  }).on(`restart`, () => {
    console.log(`App restarted!`)
  })
})
```

**Comment by RavenHursT** [comment]
Relate SO: http://stackoverflow.com/questions/35355354/gulp-nodemons-watch-w-tasks-isnt-working

**Comment by JacksonGariety** [comment]
Do `copy-assets` and `transpile` both return any streams inside of them as in [this example](https://github.com/JacksonGariety/gulp-nodemon#using-gulp-nodemon-with-react-browserify-babel-es2015-etc)?

**Comment by RavenHursT** [comment]
Yes.. both do.. But they don't store the stream in a variable before returning.. not sure if that's a big diff:

```
import gulp from 'gulp'

gulp.task(`copy:icon`, () => {
  return gulp.src(`favicon.ico`)
    .pipe(gulp.dest(`build/public`))
})

gulp.task(`copy:config`, () => {
  return gulp.src(`src/**/*.config.json`)
    .pipe(gulp.dest(`build`))
})

gulp.task(`copy:lua-scripts`, () => {
  return gulp.src(`src/util/context-builder/lua-scripts/**/*`)
    .pipe(gulp.dest(`src/util/context-builder/lua-scripts/`))
})

gulp.task(`copy-assets`, [
  `copy:icon`,
  `copy:config`,
  `copy:lua-scripts`
])
```

the `transpile` task is very similar....

**Comment by RavenHursT** [comment]
Turns out that I had another task that was loading a dependency that was opening a Redis connection and never closing that connection.  So the Node process wasn't closing, and therefor couldn't be restarted.  Closing this issue.
