### ISSUE TITLE
Make nodemon pluggable

### ISSUE THREAD

**Issue by juergenzimmermann** [JacksonGariety/gulp-nodemon#108]
It would be nice to have nodemon pluggable. Then it would be be easy to upgrade to a newer nodemon version and stay with the current gulp-nodemon version.

**Comment by JacksonGariety** [comment]
ah, this is a good idea! tagged enhancement.

**Comment by IOAyman** [comment]
That would be great! :+1:

**Comment by juergenzimmermann** [comment]
@JacksonGariety do you see a chance for this issue?

**Comment by IOAyman** [comment]
@juergenzimmermann I suggested a PR (#123) which resolves this.

Unfortunately, it seems like @JacksonGariety is not maintaining this plugin anymore (looking at his profile and response rate to issues and PRs) :disappointed: 

However, if you still need that option, you can use [my fork](https://github.com/IOAyman/gulp-nodemon/tree/ioayman-pluggable-nodemon) :smiley:

**Comment by JacksonGariety** [comment]
@IOAyman Thanks for the PRs. Merged two and left a question for review on one.

I do my best to review important issues as they arise. Mostly I think that the plugin's purpose is rather niche and lots of people want it to solve a problem which nodemon solves by itself.

It also doesn't have a test suite which makes PR review difficult.

**Comment by IOAyman** [comment]
@JacksonGariety You're welcome!
You're absolutely right! A test suite would help reviewing PRs a lot!

**Comment by JacksonGariety** [comment]
It's in
