### ISSUE TITLE
Support question - ignoring changes to any top level directory

### ISSUE THREAD

**Issue by ORESoftware** [JacksonGariety/gulp-nodemon#110]
I have this:

```js
gulp.task('nodemon', [], function () {

    nodemon({

        script: 'server/bin/www',
        ext: 'js',
        ignore: ['server/public/*', '*.git/*', '*.idea/*', 'gulpfile.js'],   //server code is one level down
        args: [], //TODO: add these from command line
        nodeArgs: ['--harmony_destructuring'],
        env: {
            NODE_ENV: $node_env  || 'development'
        }

    }).on('restart', []);

});
```

In my project, however, the server code is not at the root, but at one level down.
So I am looking for some glob pattern that can ignore any changes to any directory in the root except the server directory, hope that makes sense. Is it possible to do this? What I am looking for is basically the opposite of "ignore" something positive instead of negative like "watch".

**Comment by JacksonGariety** [comment]
You can use `"watch": []` and set it to an array of strings and use `../` in it to go up a directory and such.

**Comment by JacksonGariety** [comment]
See: https://github.com/remy/nodemon/blob/master/doc/sample-nodemon.md

**Comment by ORESoftware** [comment]
thanks Jackson, will follow that lead
