### ISSUE TITLE
running tasks through gulp.start

### ISSUE THREAD

**Issue by roymiloh** [JacksonGariety/gulp-nodemon#111]
Due the [current implementation](https://github.com/JacksonGariety/gulp-nodemon/blob/master/index.js#L80), those who try to develop, let's say, CLI that uses `gulp` internally, but the CLI itself runs inside a project that doesn't use `gulp`, the passed `tasks` are not available (there is not even a `gulpfile` in the 'client' project, which makes sense because it uses the CLI directly).

I'd suggest to use `gulp.start`, the implementation of [runSequence](https://github.com/OverZealous/run-sequence/blob/master/index.js#L88) works great for example.

wdyt?

**Comment by JacksonGariety** [comment]
@roymiloh `gulp.start` is going to be deprecated soon. Maybe it would be better to be able to provide a path to a local gulp rather than assuming a global one? Would that work for your purposes?
