### ISSUE TITLE
DoS vulnerability 

### ISSUE THREAD

**Issue by aaronroberson** [JacksonGariety/gulp-nodemon#117]
Node Security (nodesecurity.io) is reporting a vulnerability with the minimatch package this module depends upon:

 https://nodesecurity.io/advisories/118

Please see https://github.com/gulpjs/gulp/issues/1719

**Comment by JacksonGariety** [comment]
Not sure there's a DOS vulnerability here.

**Comment by danmademe** [comment]
Even if you don't think there's an issue here, it still fails NSP and nodesecurity.io because you have outdated packages.

if you want i can take over this package and update it.. since it's been dead along time

**Comment by danmademe** [comment]
@aaronroberson you should be putting gulp packages in your dev-deps
