### ISSUE TITLE
Any way to conditionally cancel nodemon restart?

### ISSUE THREAD

**Issue by jayarjo** [JacksonGariety/gulp-nodemon#128]
Sometimes it might be handy to conditionally prevent `nodemon` from restarting, for example when `.js` files that nodemon is set to monitor, are transpiled from `.ts` by watcher. So basically even if only one TypeScript file is updated, transpiler alters several `js` files (or even all) and nodemon restarts for them all..? At least I observe multiple restarts in the console. Is there a way around this?

**Comment by JacksonGariety** [comment]
Have you seen this example in the README?

    nodemon({
      script: './index.js'
    , ext: 'js css'
    , tasks: function (changedFiles) {
        var tasks = []
        changedFiles.forEach(function (file) {
          if (path.extname(file) === '.js' && !~tasks.indexOf('lint')) tasks.push('lint')
          if (path.extname(file) === '.css' && !~tasks.indexOf('cssmin')) tasks.push('cssmin')
        })
        return tasks
      }
    })

If I understand your problem correctly, you can solve it be writing a task that handles all your typescript compilation, and return `['ts']` from a function of the `tasks` property. If all goes well, nodemon will wait until that task has exited before restarting, and it should only restart once.

**Comment by jayarjo** [comment]
Will it wait if task is async? What if `tasks` is set to empty array, will it prevent `nodemon` from restarting?

**Comment by JacksonGariety** [comment]
Expected behavior is that even if the task is async, so long as it returns its own stream (example here: https://github.com/JacksonGariety/gulp-nodemon#using-gulp-nodemon-with-react-browserify-babel-es2015-etc) nodemon will use `child_process.spawnSync` to wait until completion. This is basically gulp-nodemon's core feature.

If tasks is empty the restart should be immediate.
