### ISSUE TITLE
not watching files recursively ?

### ISSUE THREAD

**Issue by andyfenelon** [JacksonGariety/gulp-nodemon#129]
```
gulp.task('default', ['watch'], () =>
  nodemon({
    script: 'index.js',
    watch: [
      //'app/views/home.hbs',
      'app/views'
    ],
    ignore: 'public'
  })
);
```

when i link to the file directly (as per the commented out line) it works. 
when i try to watch the folder 'app/views' and then make changes it dosn't seem  to register anything ?

iv'e tried a few different combinations `'app/views/**/*'` `'app/views/*.hbs'`

it's showing on run that it should be ? using the above gulp task code

`[nodemon] watching: /Users/user/Documents/myapp/app/views/**/*`

**Comment by JacksonGariety** [comment]
I was unable to reproduce this :-/

Does nodemon respond /at all/ the way you have it? Or does nothing happen?

What happens if you remove the ignore?

**Comment by andyfenelon** [comment]
thank for taking the time to look. 


it seems to be  when   `'app/views'` is included in the watch array it stops responding.


```
gulp.task('default',  () =>
  nodemon({
    script: 'index.js',
    watch: [
      'index.js', <!-- works
      'app/views/home.hbs', <!-- works
      'app/views' <!-- stops when this is added
    ],
    //ignore: 'public' <!-- tried removing 
  })
);
```
  
i do have partials in the folder so i removed them to test and its still occurring.

**Comment by andyfenelon** [comment]
it might possibly be related to this https://github.com/gilt/koa-hbs/issues/52

**Comment by andyfenelon** [comment]
ok all i need to do was add     `ext: 'hbs',`

thanks again. close.
