### ISSUE TITLE
how to add --debug?

### ISSUE THREAD

**Issue by huanganqi** [JacksonGariety/gulp-nodemon#137]
[11:46:27] [nodemon] starting `node ./index.js`

= to =>

[11:46:27] [nodemon] starting `node --debug ./index.js`

====

nodemon({
    script: './index.js',
    stdout: true,
    //debug: true, ???
})

**Comment by jerossh** [comment]
```
nodemon({
        script: 'bin/www',
        ext: 'js',
        env: { 'NODE_ENV': 'development' },
        nodeArgs: ['--debug'],
    })
```
