### ISSUE TITLE
Publish 2.3.0 to NPM

### ISSUE THREAD

**Issue by paglias** [JacksonGariety/gulp-nodemon#149]
The git repo says 2.3.0 but it's not available on npm

**Comment by rejas** [comment]
Or 2.4.0 for that matter @JacksonGariety Adding a release / tag in guthub would also already be helping.
Thanks for coming back and merging anyway!

**Comment by joebowbeer** [comment]
Please publish 2.4.0

**Comment by mikemaccana** [comment]
Heya! can you please do an `npm publish`? Thanks!

**Comment by gwhitelaw** [comment]
Hi @JacksonGariety - any update on publishing?

**Comment by joebowbeer** [comment]
In the interim, the latest commit can be installed from GitHub:

`npm install -D jacksongariety/gulp-nodemon#1a31fa2`

**Comment by markstos** [comment]
@joebowbeer  -- @JacksonGariety has been inactive for months. The project likely needs a fork and a new maintainer at this point. see  #147 for more discussion.

**Comment by JacksonGariety** [comment]
Sorry for the delay. I have published `2.4.1`.
