### ISSUE TITLE
npm audit report

### ISSUE THREAD

**Issue by AmenRa** [JacksonGariety/gulp-nodemon#157]
How can i fix these issues?
Can you update dependancies?

Thank you!

<img width="733" alt="screen shot 2018-09-12 at 17 59 57" src="https://user-images.githubusercontent.com/11797097/45437786-d98c8180-b6b5-11e8-8278-606de6740272.png">

<img width="729" alt="screen shot 2018-09-12 at 18 00 21" src="https://user-images.githubusercontent.com/11797097/45437806-e4471680-b6b5-11e8-8f98-7a25c090c827.png">

<img width="731" alt="screen shot 2018-09-12 at 18 00 48" src="https://user-images.githubusercontent.com/11797097/45437818-e90bca80-b6b5-11e8-81dc-a4d57c1a5ea8.png">

**Comment by gabinho5** [comment]
It seems that the master branch gulp dependency has already been updated to gulp: "^4.0.0" which should resolve the issue, but the update needs to be released! @JacksonGariety Could you publish the newest version?

**Comment by JemiloII** [comment]
Waiting for this as well :)

**Comment by kkoyot** [comment]
+1, it's just a matter of creating a new tag and publishing to npm. Can we count on you, @JacksonGariety ?

**Comment by JemiloII** [comment]
So I did a little more poking around. gulp 4 isn't quite ready as it has some breaking changes from the 3.9.1 release. Probably better to wait until gulp is 4.0.0, plus, minimatch isn't an issue unless your having user supplied data in your gulp build process. If you do, I'd recommend you'd fix that~

**Comment by joebowbeer** [comment]
Depends on #149

**Comment by joebowbeer** [comment]
@JemiloII gulp 4 has been released via the @next tag.

**Comment by hadifarnoud** [comment]
updates? shall I remove gulp-nodemon until release?

**Comment by JemiloII** [comment]
@joebowbeer just because it has a `@next` doesn't mean its ready. If it was, it wouldn't be next but the stable release.

**Comment by joebowbeer** [comment]
Fixed by v2.4.1 release

**Comment by JacksonGariety** [comment]
Audited.
