### ISSUE TITLE
Critical Vulnerability

### ISSUE THREAD

**Issue by jrwiegand** [JacksonGariety/gulp-nodemon#163]
A critical vulnerability has popped up today with `event-stream`, can this be updated ASAP?

### Related links:
- https://www.npmjs.com/advisories/737
- https://github.com/dominictarr/event-stream/issues/116
- https://github.com/remy/nodemon/issues/1469

### NPM Audit
```
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Malicious Package                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ flatmap-stream                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp-nodemon [dev]                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp-nodemon > event-stream > flatmap-stream                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/737                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Malicious Package                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ flatmap-stream                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp-nodemon [dev]                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp-nodemon > nodemon > pstree.remy > ps-tree >             │
│               │ event-stream > flatmap-stream                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/737                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Malicious Package                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ flatmap-stream                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nodemon [dev]                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nodemon > pstree.remy > ps-tree > event-stream >             │
│               │ flatmap-stream                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/737                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 3 critical severity vulnerabilities in 17907 scanned packages
  3 vulnerabilities require manual review. See the full report for details.
```

**Comment by yoelfme** [comment]
any update about this?, is going to be really helpful, please, merge the PR :+1:

**Comment by aal89** [comment]
Yeah, but which one? Mine or @sebaplaza's one?

I might be missing something but I am not trusting @right9ctrl right now. So I followed advise and not updated to version 4 of `event-stream`, instead pinned it to version 3.3.4 so that all malicious version in peoples cache also gets flushed. This also means my PR is of lowest impact.

Not sure which one is better tho. Do people have any ideas on which one to merge?

**Comment by yoelfme** [comment]
@aal89 yours, because the recommended action is update `event-stream` to `3.3.4`, so your PR makes the same thing that people in `ps-tree` did https://github.com/indexzero/ps-tree/pull/34/files, go ahead!

**Comment by sebaplaza** [comment]
@aal89 i agree with you, the v4 was possibly created to hide the old malicious code.

anyways, the v4 also add the flatmap function (a clean one).
https://github.com/dominictarr/event-stream/commit/908fee5c65d4eb02809a84a1ebc3e5df1f935cd1

and flatmap-stream dependency has been removed
https://github.com/dominictarr/event-stream/commit/2bd63d58fe24367372690c29c7249ed1c7145601

@right9ctrl user doesn't exists anymore on github, and the repo owner is still @dominictarr.

npm owner has been removed too.

```sh
$ npm owner ls event-stream
npm <npm@npmjs.com>
```
We must upgrade old nodemon dependency too.

**Comment by yoelfme** [comment]
so the final PR will include lock the `event-stream` package and upgrade `nodemon`?

**Comment by aflext** [comment]
Why haven't this issue been solved? So many days have past

**Comment by aal89** [comment]
I have updated my PR removing the `event-stream` dependency entirely and also updated `nodemon` to `1.18.7`. The test ran fine(?). Why was it being used in the first place?

**Comment by sebaplaza** [comment]
you're right @aal89, `event-stream` is not being used at all. So, if @JacksonGariety is ok, we should remove `event-stream` dependency.

looking at the source, the module `colors` is useless too.

i think this project needs a clean up.

about your PR, i think you should commit `package-lock.json` too, as a good practice.

**Comment by aal89** [comment]
Yeah you're right, this project could use cleaning. Right now I'm going to stay focussed on this issue alone. I will update the PR and include the `package-lock.json` too. Thanks for the feedback!

**Comment by sebaplaza** [comment]
Well, this is not anymore a vulnerability, as you know `event-stream@3.3.6` has been unpublished.
This means that gulp-nodemon is actually **broken**.

Well, as a workaround, you can use @aal89 version...

```json
    "gulp-nodemon": "github:aal89/gulp-nodemon#8c46ee1ffe02c4b80b0452bd6b3b8c587ab17b79",
```

**Comment by jrwiegand** [comment]
I am not sure if others have reached out to @JacksonGariety but he seems quite unresponsive. I think the workaround may be the best bet for the near-future. I hope that I am wrong.

**Comment by simison** [comment]
>I am not sure if others have reached out to @JacksonGariety but he seems quite unresponsive.

2-3 days to respond isn't that long time to wait in open source world, especially in the middle of the week. ;-)

Pinged directly at https://github.com/JacksonGariety/gulp-nodemon/pull/164#issuecomment-442464510

**Comment by binarykitchen** [comment]
yeah come on, it's important - waiting here too!

**Comment by binarykitchen** [comment]
Looks like it's done but not on npm yet ... publish it now?

**Comment by jrwiegand** [comment]
> Looks like it's done but not on npm yet ... publish it now?

@binarykitchen Version 2.4.2 is the fixed version and that version is published to npm.

See here: https://www.npmjs.com/package/gulp-nodemon

@JacksonGariety Has not yet created a 2.4.2 release on GitHub.

**Comment by binarykitchen** [comment]
well @jrwiegand, `yarn outdated` gives me a different version:

```
└─❱❱❱ yarn outdated                                                                                                                                                    +9998 17:40 ❰─┘
yarn outdated v1.12.3
info Color legend :
 "<red>"    : Major Update backward-incompatible updates
 "<yellow>" : Minor Update backward-compatible features
 "<green>"  : Patch Update backward-compatible bug fixes
Package       Current Wanted Latest Package Type    URL
gulp-nodemon  2.4.1   exotic exotic devDependencies github:aal89/gulp-nodemon#8c46ee1ffe02c4b80b0452bd6b3b8c587ab17b79
```

Why it is suggesting `exotic` over `2.4.2` and why is the URL pointing to a fork, from github:aal89/gulp-nodemon?

**Comment by jrwiegand** [comment]
@binarykitchen I do not use yarn and cannot speak to the reason that package would be outdated there. It is clearly available in npm's registry as I comment above.
