### ISSUE TITLE
Wait for 'change' event to finish before restarting

### ISSUE THREAD

**Issue by JacksonGariety** [JacksonGariety/gulp-nodemon#20]
Right now the change even has a problem. It'll run your tasks, but if they don't finish before nodemon kills and restarts the server, the changes won't be reflected in the app. Nodemon needs support for this, as I'm not sure it's possible.

The nodemon solution is to use `exec`, but the only last step towards JS build system bliss is keeping all of your tasks in one process, and exec creates child processes. `gulp-nodemon`'s goal is to fix this, but nodemon needs a way to delay building before change first.

**Comment by iksose** [comment]
:+1:

**Comment by JacksonGariety** [comment]
Solution is included in gulp-nodemon 2.0.0 for those interested. Docs here: https://github.com/jacksongariety/gulp-nodemon#synchronous-build-tasks
