### ISSUE TITLE
ignore files not ignored

### ISSUE THREAD

**Issue by gmoulin** [JacksonGariety/gulp-nodemon#24]
Hi,
I managed to get nodemon running but the ignore file option is not taken into account.

```javascript
gulp.task('nodemon-dev', function( cb ){
	p.nodemon({
		script: 'server.js',
		nodeArgs: ['--debug=9999'], 
		ignore: [
			'./!(server)/**',
			'./Gruntfile.js',
			'./gulpfile.js'
		],
		ext: 'js',
		delayTime: 1,
		env: {
			ENV: 'development',
			PORT: 3001
		}
	});

	cb( null );
});
```

I want the server to reload on javascript files change in "server/" folder and "server.js" main file.
Problem is when I save "gulpfile.js" or any other js file nodemon restart.

**Comment by c0bra** [comment]
I was getting the `this might cause high cpu usage` warning as well, however it seemed like only changes to the files in my `watch` property triggered a restart.

I changed my watch from `src/server/` to `./src/server` as @ilanbiala indicated and the warning went away.

**Comment by JacksonGariety** [comment]
@AndrewGrachov is right, in this case.

**Comment by richburdon** [comment]
I can't selectively ignore a sub folder that is being watched.

~~~~
{
  "watch": [
    "src/server"
  ],

  "ignore": [
    "src/server/views/*"
  ]
}
~~~~

**Comment by benjamin21st** [comment]
You can watch individual files as well.
