### ISSUE TITLE
cwd option sets the process working directory

### ISSUE THREAD

**Issue by ericeslinger** [JacksonGariety/gulp-nodemon#38]
I don't know if this is intended behavior or not, but I observed this behavior:

    gulp.task 'backend:serve', ['backend:build', 'backend:copy'],  ->
      plugins.nodemon
        cwd: config.paths.backendBuild
        script: "server.js"

would set my process-wide CWD to the backendBuild location. This caused other issues in my build - any created gulp.src streams that happened afterwards would be relative to project/backend instead of project. I switched to using `watch: 'backend', script: 'backend/server.js'` instead.

**Comment by JacksonGariety** [comment]
@ericeslinger gulp-nodemon keeps the development cycle all under one process. This means that, yes, changing the gulp-nodemon cwd will set the starting cwd for your app. using `watch:` and `script:` is the standard in this case.
