### ISSUE TITLE
nodemon 1.3.x breaks gulp-nodemon

### ISSUE THREAD

**Issue by jedverity** [JacksonGariety/gulp-nodemon#49]
I specify an option like so:

    script: './server/server.js'

nodemon looks to my package.json `scripts.start` property, which has `gulp` specified, and then tries to run `gulp ./server/server.js`.

Removing scripts.start from package.json solves the problem, but I don't want to do that. How can I remedy this?

It works fine with nodemon 1.2.x.

**Comment by jedverity** [comment]
See here for reference: https://github.com/remy/nodemon/commit/b70b81612c403a6d92ad262ac9298c459405579c

So not just 1.3.x, but latest.

**Comment by jedverity** [comment]
also for reference: https://github.com/remy/nodemon/issues/439

so seems best to revert your nodemon dependency to 1.2.1 for now.

**Comment by remy** [comment]
nodemon 1.3.0-x isn't not stable yet. It's also not marked as latest, it it automatically upgrading?

**Comment by jedverity** [comment]
Ah yes I saw that in the other referenced comment. It is indeed
automatically upgrading to 1.3.0-6.

**Comment by JacksonGariety** [comment]
Hmmmm I can't reproduce this error. Was it fixed on 1.3.0-7?

**Comment by davisford** [comment]
Just a me too.  `gulp-nodemon@1.0.5` fails my build with:

```
[gulp] [nodemon] watching extensions: undefined
[gulp] [nodemon] starting `gulp ./src/server/bin/www`
```

Whereas, when I roll back to `1.0.4` all is well:

```
[gulp] [nodemon] watching extensions: js,jade,html,css,styl,json
[gulp] [nodemon] starting `node --debug ./src/server/bin/www`
```

This is the task in question that I'm running for nodemon:

````javascript
gulp.task('nodemon', function () {
  plugins.nodemon({
    script: './src/server/bin/www',
    verbose: true,
    env: {
      'NODE_ENV': 'development',
      'DEBUG': '* -express:* -send -session -mquery -express-session -engine* -socket.io:* -socket.io-parser -morgan -connect* -stylus*'
    },
    watch: './src/server',
    ext: 'js jade html css styl json',
    nodeArgs: ['--debug']
  }).on('restart', function () {
    // initiate livereload -- sometimes happens too fast; 500 ms was too short for me
    setTimeout(function () {
      log('Trying to refresh livereload after server has restarted...');
      reload.changed('/');
    }, 1000);
  });
});
```

**Comment by nmccready** [comment]
Ditto this is putting us in a gulp loop

**Comment by devourment77** [comment]
Same thing is happening to me.   I only ran an NPM update (and it seemed to work fine with nodemon 1.2.1).

        ip-192-168-1-42: brandon$ gulp
        [14:20:57] Using gulpfile ~/git/dev/gulpFile.js
        [14:20:57] Starting 'loadConfig'...
        NODE_ENV is not defined! Using default development environment
        [14:20:57] Finished 'loadConfig' after 4.41 ms
        [14:20:57] Starting 'nodemon'...
        [14:20:57] Starting 'watch'...
        [14:20:57] Finished 'watch' after 31 ms
        [14:20:57] Live reload server listening on: 35729
        [gulp] [nodemon] v1.3.0-7
        [gulp] [nodemon] to restart at any time, enter `rs`
        [gulp] [nodemon] watching: *.*
        [gulp] [nodemon] starting `gulp server.js`
        [14:20:58] Using gulpfile ~/git/dev/gulpFile.js
        [14:20:58] Task 'server.js' is not in your gulpfile
        [14:20:58] Please check the documentation for proper gulpfile formatting
        [gulp] [nodemon] app crashed - waiting for file changes before starting...

**Comment by remy** [comment]
1.3.1 is now published. Hopefully it doesn't screw anything up for you folk?! :)

**Comment by JacksonGariety** [comment]
@devourment77 could you debug that `Task 'server.js' is not in your gulpfile` warning to make sure that's not crashing it? I can't reproduce for some reason. Maybe I have an old nodemon version or something.

**Comment by JacksonGariety** [comment]
@devourment77 @remy still can't reproduce this on my end. I get:

    [gulp] [nodemon] v1.3.1
    [gulp] [nodemon] to restart at any time, enter `rs`
    [gulp] [nodemon] ignoring: /Users/Jackson/Sites/gulp-nodemon/.git/**/* /Users/Jackson/Sites/gulp-nodemon/node_modules/**/* bower_components .sass-cache
    [gulp] [nodemon] watching: /Users/Jackson/Sites/gulp-nodemon/**/*
    [gulp] [nodemon] watching extensions: js,coffee
    [gulp] [nodemon] starting `node ./test/server.js`
    [gulp] [nodemon] child pid: 57155
    [gulp] [nodemon] watching 8 files
    foo
    [gulp] [nodemon] clean exit - waiting for changes before restart
    [gulp] [nodemon] exiting

Tried with nodemon `1.3.0-7` and `1.3.1` both worked.

**Comment by devourment77** [comment]
Here's my gulpFile.js and package.json snippet...  I normally just go to my git repo and type "gulp" and it loads my default.  Oddly, when I remove "start": "gulp" from my scripts in package.json, it seems to work with 1.0.5, but I have no idea why.  Also downgrading to gulp-nodemon 1.0.4 seems to also fix the issue (while letting me keep the line in my package.json).

PACKAGE.JSON

            "scripts": {
                "start": "gulp",
                "test": "gulp test",
                "postinstall": "bower install --config.interactive=false"
            },


GULP FILE

        'use strict';

        // load plugins and modules
        var gulp = require('gulp');
        var jshint = require('gulp-jshint');
        var nodemon = require('gulp-nodemon');
        var livereload = require('gulp-livereload');
        var uglify = require('gulp-uglify');
        var concat = require('gulp-concat');
        var rename = require('gulp-rename');
        var karma = require('gulp-karma');
        var stripDebug = require('gulp-strip-debug');
        var sourcemaps = require('gulp-sourcemaps');
        var templateCache = require('gulp-angular-templatecache');
        var watch = require('gulp-watch');


        /**
         * Vars to be used with loadConfig. See loadConfig task and the config folder.
         */
        var applicationJavaScriptFiles,
            applicationJavaScriptDepFiles,
            applicationTestFiles,
            applicationPartialFiles;

        /**
         * Run js lint on our files to look for errors.  This includes express and angular js files (server / public).
         */
        gulp.task('jshint', function() {
            gulp.src(['gulpFile.js', 'server.js', 'config/**/*.js', 'app/**/*.js', 'public/js/*.js', 'public/js/modules/*.js'])
                .pipe(jshint())
                .pipe(jshint.reporter('default'));
        });

        /**
         * Enable nodemon and set environment to development so we can run a server locally and reload files.
         */
        gulp.task('nodemon', function (done) {
            nodemon({
                script: 'server.js',
                ext: 'html js',
                ignore: ['public/*', 'node_modules/*'],
                env: { 'NODE_ENV': 'development' }
            }).on('restart');
        });

        /**
         * Minify the public JS and strip comments.
         */
        gulp.task('uglify', function() {
            gulp.src(applicationJavaScriptFiles)
            .pipe(sourcemaps.init())
                .pipe(concat('application.min.js'))
                //.pipe(ngAnnotate())
                .pipe(stripDebug())
                .pipe(uglify())
            .pipe(sourcemaps.write('./'))
            .pipe(gulp.dest('public/js/dist'));
        });

        /**
         * Minify the public JS dependencies EXCEPT for jquery and angular (served from CDN)
         */
        gulp.task('uglifyModules', function() {

            // remove jquery and angular from being minified, this is because they will be from CDN.
            // assumption is they are the first two files.
            var cleanJavaScriptDepFiles = applicationJavaScriptDepFiles.slice(2);

            gulp.src(cleanJavaScriptDepFiles)
            //.pipe(sourcemaps.init())
                .pipe(concat('angular_modules.min.js'))
                //.pipe(ngAnnotate())
                //.pipe(stripDebug())
                //.pipe(uglify())
            .pipe(sourcemaps.write('./'))
            .pipe(gulp.dest('public/js/dist'));
        });

        /**
         * Minify and store all html partials into a single js for template cache.
         */
        gulp.task('templateCache', function () {
            gulp.src(applicationPartialFiles)
                .pipe(templateCache('templates.min.js', {
                    //standalone: true,
                    root: 'partials',
                    module: 'core'
                }))
                .pipe(uglify())
                .pipe(gulp.dest('public/js/dist'));
        });

        /**
         * Run karma unit tests in "test" environment.
         */
        gulp.task('karma', function () {
            process.env.NODE_ENV = 'test';
            gulp.src(applicationTestFiles)
            .pipe(karma({
                configFile: 'tests/karma.conf.js',
                action: 'start'
            }))
            .on('error', function(err) {
                // Make sure failed tests cause gulp to exit non-zero
                throw err;
            });
        });

        /**
         * Watch for file changes, re-minify public js, then live reload the js.
         */
        gulp.task('watch', function() {
            livereload.listen();
            var server = livereload();
            //gulp.watch(['gulpFile.js', 'server.js', 'config/**/*.js', 'app/**/*.js', 'public/js/**/*.js', 'public/modules/**/*.js'], ['jshint']);

            //gulp.watch(['public/js/*.js', 'public/js/modules/**/*.js'], ['uglify']);

            gulp.watch(['config/**/*.js', 'app/**/*.js', 'public/partials/*.html', 'public/css/*.css', 'public/js/*.js', 'public/js/modules/**/*.js']).on('change', function(file) {
                server.changed(file.path);
            });
        });

        /**
         * Load our application config files.  See the config folder.
         */
        gulp.task('loadConfig', function() {
            var init = require('./config/init')();
            var config = require('./config/config');
            applicationJavaScriptFiles = config.assets.js.concat(config.assets.productionJs);
            applicationJavaScriptDepFiles = config.assets.lib.js;
            applicationTestFiles = config.assets.lib.js.concat(config.assets.js, config.assets.tests);
            applicationPartialFiles = config.assets.partials;
        });

        /**
         * Bundle tasks for the default "gulp" command.
         */
        gulp.task('default', ['loadConfig', 'nodemon', 'watch']);

        /**
         * Shortcut for js lint.
         */
        gulp.task('lint', ['jshint']);

        /**
         * One time minify public js.
         */
        gulp.task('build', ['jshint', 'loadConfig', 'uglify', 'uglifyModules', 'templateCache']);

        /**
         * Shortcut to run karma tests.
         */
        gulp.task('test', ['loadConfig', 'karma']);

**Comment by JacksonGariety** [comment]
@devourment77 @remy so this problem is [within nodemon's `exec.js` file on this line](https://github.com/remy/nodemon/blob/master/lib/config/exec.js#L135).

Nodemon `1.3.x` instead of defaulting to `"node"` uses the primary executable command which, for gulp users, would simply be `gulp` thus causing a loop.

## Temporary Fix
add `exec: 'node'` to your `gulp-nodemon` config to temporarily fix the issue

## Dear Remy
I'm curious why nodemon no longer defaults to node and instead uses the primary process command. Should it not always default to node? The question is, do people more often use `require('nodemon')` to programmatically invoke nodemon form the console (in which case default to node would be wise) or actually use nodemon as part of their application. This latter case seems like the rarer one to me so I'd probably suggest changing [lines 131 to 144 of exec.js]((https://github.com/remy/nodemon/blob/master/lib/config/exec.js#L135) to the following:

    nodemonOptions.exec = nodemonOptions.exec || 'node';

**Comment by OscarGodson** [comment]
@JacksonGariety they use nodemon to restart other other processes like python or io.js

**Comment by JacksonGariety** [comment]
@OscarGodson that's what the `--exec` arg is for, right? no need to default away from node I mean that won't make it more convenient, right?

**Comment by jedverity** [comment]
I still have the same issue, unfortunately. Adding `exec: node` to nodemon options in `gulpfile.js` runs `gulp node server/server.js`, pulling `gulp` from `scripts.start` in package.json.

I forked gulp-nodemon and set the nodemon dependency to 1.2.1 and it works as expected.

**Comment by neagle** [comment]
@jedverity Thanks for forking `gulp-nodemon`: I went ahead and used your fork to solve my identical problem, for the moment. @JacksonGariety's solution didn't work for me, either.

**Comment by JacksonGariety** [comment]
@remy could you take a look at @jedverity's comment? Thanks.

**Comment by remy** [comment]
So, you looked at the [blame and commit](https://github.com/remy/nodemon/commit/66e71d6b6406a679ce257da03fde887e970824d3) log right? There's your answer initially (as to why `exec.found` is used).

nodemon doesn't default to nothing and does not require that `exec="node"` be used. Certainly I used nodemon every day and I don't have to do this (and I don't use an execMap).

So, the bigger question is how on earth is nodemon picking up gulp? 

I think it would actually be pretty useful to see some tests, or a super boiled down version that replicates the issue. Please note - and this is **super important**: I don't use gulp, I never have, so when you post the directions, please add **everything** - so I can setup gulp etc.

**Comment by remy** [comment]
To add...if you folk are using package.start and point to `gulp`, and *nothing* else, then is going to use the package.start to run the code. This was always intended functionality. I think the issue lies around this code, but until I can replicate, then I can't dig in.

Of course, if anyone else wants to have a go too, that would be extremely useful.

**Comment by OscarGodson** [comment]
FWIW I've been using vanilla nodemon without setting a default process or anything.

**Comment by JacksonGariety** [comment]
@remy Thanks for taking the time to respond. I really enjoy these tools and am happy to work on them.

I can reproduce this issue using only `nodemon 1.3.1` itself. At least, I believe that it's the same issue; it may simply be a similar one.

Here's how I produced it:

1. `npm install nodemon`
2. `touch start_nodemon.js package.json`
3. put this in _package.json_: `{ "scripts": { "start": "foo" } }`
4. and this in _start_nodemon.js_: `require('nodemon')({ script: 'server.js' })`

Then execute `node start_nodemon.js` in the shell:

    sh: foo: command not found

Nodemon picks up `scripts.start` even if `npm start` is not invoked. I believe that this is what's causing the above circular gulp invocation.

**Comment by remy** [comment]
Perfect, the passed in script should take precedence over `package.start`. I'll start a PR.

**Comment by devourment77** [comment]
For now, I'll just remove the start: gulp line from my package.json scripts (as that seems to be working) and I'll add it back once the PR is live.

Thank you all!
Brandon

**Comment by remy** [comment]
PR in progress...

**Comment by remy** [comment]
:ship:'d :point_left: live in 1.3.2.

**Comment by jedverity** [comment]
Works like a dream, thx @remy (and all who helped track it down)!

**Comment by JacksonGariety** [comment]
thank you @remy
