### ISSUE TITLE
How to emit event back to the child process?

### ISSUE THREAD

**Issue by binarykitchen** [JacksonGariety/gulp-nodemon#50]
Is there a chance I can emit something back to the child from a gulp task?

**Comment by remy** [comment]
I don't use gulp, so I don't know. Give me some example, *keep it simple* and I might be able to tell you.

**Comment by remy** [comment]
(deleted my comment, I thought I was on the nodemon repo!! :)

**Comment by sbehun** [comment]
Looking to do the same thing here.  Did you ever find a fix?

One gulp task starts the server, another task needs to be able to stop it.  I would expect something like...
```
$.nodemon.emit('quit');
```
to kill the server.  Instead I get the following error:
```
D:\project\gulpfile.js:36
    $.nodemon.emit('quit');
              ^
TypeError: undefined is not a function
    at Stream.<anonymous> (D:\project\gulpfile.js:36:15)
    at Stream.emit (events.js:129:20)
    at ChildProcess.<anonymous> (D:\project\node_modules\gulp-protractor\index.js:66:13)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
```

**Comment by edwardwang1105** [comment]
My current workaround is to replace the `gulp-nodemon` with `nodemon`.

```javascript
var nodemon = require('nodemon');

gulp.task('nodemon', function(cb) {
    return nodemon({ script: 'app.js' });
});

// Task wants to stop nodemon, e.g. mocha-phantomjs
gulp.task('test', ['nodemon'], function() {
  return gulp.src('')
    .pipe($.shell(mochaPhantomjsPath + ' http://localhost:3000/test.html'))
    .once('end', function() {
      nodemon.emit('quit');
    });
});
```

**Comment by JacksonGariety** [comment]
@edwardwang1105 does nodemon.emit('quit') not work with gulp-nodemon? Is an error thrown?

**Comment by JacksonGariety** [comment]
@binarykitchen were you trying to do something like `child_process.send()` with a message? If so, you might want to use net sockets.

**Comment by binarykitchen** [comment]
i don't remember my problem anymore, this ticket is so old and after six months you are replying ...

**Comment by edwardwang1105** [comment]
@JacksonGariety just like @sbehun said, it throws `TypeError: undefined is not a function` when calling `$.nodemon.emit('quit')`

**Comment by staff0rd** [comment]
I'd like to emit the 'restart' event to override the current crash functionality (which is to wait for a change to trigger a restart). Similar to the above comments I'm getting `nodemon.emit is not a function`.

**Comment by JacksonGariety** [comment]
@staff0rd stack trace?

**Comment by staff0rd** [comment]
~~~
TypeError: plugins.nodemon.emit is not a function
    at null.<anonymous> (c:\git\hurryup\gulpfile.js:38:21)
    at emitNone (events.js:85:20)
    at emit (events.js:179:7)
    at ChildProcess.<anonymous> (c:\git\hurryup\node_modules\nodemon\lib\monitor\run.js:153:11)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
~~~

**Comment by JacksonGariety** [comment]
@staff0rd right. being able to add an emit method may be trivial, but at the time I don't have time to find out. :-(

I do have time to review a pull request, though! :-)

**Comment by staff0rd** [comment]
I took a look at the source, and `emit()` is in fact being exposed.  In my case the error was specific to using gulp-load-plugins.  I was doing this;
~~~javascript
plugins.nodemon({
    ...
}).on('crash', function () {
    plugins.nodemon.emit('restart');
});
~~~

when instead I should have been doing something like this;

~~~javascript
var nodemon = plugins.nodemon({
    ...
});
nodemon.on('crash', function () {
    nodemon.emit('restart');
});
~~~

Considering `emit` _is_ available, this issue should probably be closed...

**Comment by JacksonGariety** [comment]
Will go out with next release
