### ISSUE TITLE
Errors when adding tasks

### ISSUE THREAD

**Issue by bsiddiqui** [JacksonGariety/gulp-nodemon#51]
When I add tasks to listeners I get an error:
`TypeError: listener must be a function`

This works:
```js
gulp.task('start', ['lint', 'style'], function () {
  nodemon({
    script: './src/server.js',
    ignore: ['./node_modules/'],
    stdout: false
  })
   .on('change', function () {
     console.log('changed');
  });
});
```

This does not:
```js
gulp.task('start', ['lint', 'style'], function () {
  nodemon({
    script: './src/server.js',
    ignore: ['./node_modules/'],
    stdout: false
  })
   .on('change', ['lint'], function () {
     console.log('changed');
  });
});
```

**Comment by JacksonGariety** [comment]
@bsiddiqui this may just be my misunderstanding node event listeners, but shouldn't the function be the second element in the array? Like this:

    .on('change', ['lint', function () {}])

If it's node standards to `.slice` off the first arg and `.join` the rest recursively I can do that pretty easily. Did a quick search but couldn't find an example of this.

**Comment by JacksonGariety** [comment]
@bsiddiqui this doesn't seem to be node standard to I'll close this.

**Comment by bsiddiqui** [comment]
@JacksonGariety yeah that makes sense. I was writing in the style that gulp defines task dependencies (see how start task has dependencies of `style` and `lint` and then defines function that's executed) instead of how node does event listeners.
