### ISSUE TITLE
Support running tasks based on which files changed

### ISSUE THREAD

**Issue by Naatan** [JacksonGariety/gulp-nodemon#56]
My primary use right now is to have it rebuild scss and uglify js files, but when I modify a JS file I dont need it to rebuild my SCSS. It'd be great if I were able to have it run tasks based on the files that were modified.

**Comment by paislee** [comment]
+1

**Comment by jasonmerino** [comment]
+1

**Comment by JacksonGariety** [comment]
You should be able to do this pretty easily:

      .on('restart', function (files) {
        var runJS = false
          , runCSS = false
    
        files.forEach(function (file) {
          switch (path.extname(file)) {
            case '.js':
              runJS = true
              break
            case '.css':
              runCSS = true
              break
          }
        })
    
        if (runJS) gulp.start.apply(gulp, ['uglify'])
        if (runCSS) gulp.start.apply(gulp, ['sass'])
      })

Unfortunately there's a bug that's going to make this difficult. If your build task ends up taking longer than the time for your app to start, the changes won't be reflected. See #20 for more info on this. It's sort irritating but you can simply make your app stall for a few seconds when it starts before it starts reading your files. Nodemon lacks a `onRestart` callback.

**Comment by JacksonGariety** [comment]
Realized that the file list isn't being fed to `change` like it is in `restart`. Decided to go ahead and overhaul this feature and close #20 in the process. Major version coming shortly.

**Comment by JacksonGariety** [comment]
@Naatan @paislee @jasonmerino take a look here guys: https://github.com/jacksongariety/gulp-nodemon#synchronous-build-tasks

Hopefully this works for you!

**Comment by jasonmerino** [comment]
@JacksonGariety I'm trying out 2.0.0 and the first time a watched file is saved it runs the correct gulp task for the file extension, but when I save a file with a different extension then it still runs the task defined for the first saved file. The task to run doesn't update after the first save after startup.

**Comment by JacksonGariety** [comment]
@jasonmerino maybe there's a bug in my changedFiles function. It's sort of pseudocode tbh I bet there's an easier way to do it with highland.js where the margin of error is smaller. Are you using it exactly as I wrote it?

**Comment by JacksonGariety** [comment]
@jasonmerino Fixed in 2.0.1 try the latest.

**Comment by jasonmerino** [comment]
Works. :) Thanks!
