### ISSUE TITLE
Watch option doesn't seem to do anything when files change

### ISSUE THREAD

**Issue by mikemaccana** [JacksonGariety/gulp-nodemon#59]
On the command line, running:

    nodemon bin/www --ext md --verbose --watch blog

Works fine - changing any file in /blog/*.md will make nodemon reload. 

Using gulp-modemon, however:

    nodemon({ script: 'bin/www', options: '--ext md --verbose --watch blog' })

Changing any file in /blog/*.md doesn't restart nodemon. 

Also should I be using gulp.watch() to trigger nodemon, like other tools? I couldn't find an example of this in the docs.

**Comment by blacksonic** [comment]
Same here.

**Comment by JacksonGariety** [comment]
@mikemaccana I'm not sure where you're seeing this `options:` property in either gulp-nodemon or nodemon config. Try using the options individually (i.e `{ext: 'md'}`).
