### ISSUE TITLE
new "tasks" support does not work on node.js 0.10

### ISSUE THREAD

**Issue by nubs** [JacksonGariety/gulp-nodemon#64]
The "tasks" code uses `child_process.spawnSync` which wasn't introduced until node.js 0.12.

**Comment by JacksonGariety** [comment]
@nubs yes, unfortunately node 0.12 allows me to intercept the nodemon loop with `spawnSync`. No other way unless remy decides to provide internal support.

**Comment by nubs** [comment]
gotcha.  Is it documented anywhere that node.js 0.12 is required for that feature?

**Comment by JacksonGariety** [comment]
@nubs I'll add it to the README now. You can still use gulp-nodemon and the `.on('restart')` event but not synchronous build tasks, that's a brand new feature.

**Comment by nubs** [comment]
Awesome thanks!
