### ISSUE TITLE
TypeError: Object #<Object> has no method 'spawnSync'

### ISSUE THREAD

**Issue by 360disrupt** [JacksonGariety/gulp-nodemon#67]
My gulp configuration starts fine but on any file change it crashes. See the full source code at:
http://stackoverflow.com/questions/29537554/gulp-nodemon-browsersync-has-no-method-spawnsync-long-loading-time

It only fails if there are tasks. Fyi cp = child process: https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options

```/Users/MasterG/Desktop/PROJEKTE/gideon/node_modules/gulp-nodemon/index.js:76
    cp.spawnSync('gulp', tasks, { stdio: [0, 1, 2] })
       ^
TypeError: Object #<Object> has no method 'spawnSync'```

**Comment by 360disrupt** [comment]
Seemed only to exist in node v0.11.16, upgrading to v0.12 solved the problem

**Comment by grit96** [comment]
I also have this issue on node `v0.10.25` gulp-nodemon `2.0.3`

**Comment by Warrenn** [comment]
I have the same issue my node version is v0.12.2 and my gulp-nodemon 2.0.3 so I'm at a loss? This sucks!
