### ISSUE TITLE
nodemon synchronously task execution not working

### ISSUE THREAD

**Issue by mauropalsgraaf** [JacksonGariety/gulp-nodemon#78]
Hello,

Been working with nodemon for a while now, but i'm not able to execute a gulp task to transform my ecmascript 6 code before the server restarts. This is a different task in tasks. My code looks like this:

    var gulp = require('gulp');
    var noDemon = require('nodemon');
    var babel = require('gulp-babel');
    var plumber = require('gulp-plumber');

    gulp.task('server', ['transformES6'], function () {
      noDemon({
        script : 'server/dist/server.js',
        ext : 'js',

        env : {
          PORT : 8000
        },
        ignore : [
          './node_modules/**',
          './server/dist/**'
        ],
        tasks : ['transformES6']
      }).on('restart', function () {
        var now = new Date();
        console.log('server is restarting: ' + now.getHours() + ' Hours, ' + now.getMinutes() + ' Minutes, ' +                 now.getSeconds() + ' Seconds');
      });
    });

    gulp.task('transformES6', function () {
      return gulp.src(['./server/**/**/**/**/*.js', '!./server/dist/'])
        .pipe(plumber())
        .pipe(babel())
        .pipe(gulp.dest('./server/dist/'));
    })

Got node v0.12.6, i suppose this is good enough, since documentation says v0.12.0. Included gulp-task transformES6 in tasks, so following documentation, it should be fine.

Thanks in advance,

Mauro Palsgraaf

**Comment by luketurner** [comment]
I also found this problem, and it seems to have two underlying causes. 

The first is that the way it determines when to run the tasks does not work if `verbose` is disabled. It looks for the line `restarting due to changes...` but that line doesn't appear to be written to `stdout` each time a file is changed, so the tasks are not triggered.

The second is that if you are on Windows you may have a problem with the way it spawns the process, because it launches the executable `gulp`, but on Windows the actual executable is called `gulp.cmd`.

**Comment by jgroblesr85** [comment]
I had same problem on Windows and @luketurner solution about changing gulp to gulp.cmd worked.

**Comment by devinmcinnis** [comment]
I know it's not ideal but, for now, you can start the task from the `restart` event:

```
  gulp.task('nodemon', function() {
    plugin.nodemon({
      script: 'app.js',
      watch: ['app.js', 'src/']
    }).on('restart', function() {
      gulp.start('transformES6');
    });
  });
```

**Comment by mauropalsgraaf** [comment]
Thanks for replying to this post, i will try it out today, have been busy for a while and the first solution from @luketurner sounds to work. @devinmcinnis, your solution will not work correctly since the on restart event will be called, but you cannot guarantee that the task will be finished before restart.
