### ISSUE TITLE
.on('exit', ...) event is being called twice

### ISSUE THREAD

**Issue by calekennedy** [JacksonGariety/gulp-nodemon#79]
```javascript
/* code snippet */

gulp.task('start', 'test', function () {
  nodemon({
    script: 'app.js',
    ext: 'js',
    watch: [
      './Common/**/*',
      './routes/**/*.js',
      './app.js'
    ]})
    .on('restart', 'test')
    .on('exit', 'stop');
});
```

The stop gulp task is being called twice. Any ideas?

**Comment by JacksonGariety** [comment]
@calekennedy 'stop' is automatically called on 'exit' to account for bugs across systems iirc. You should just be able to remove that line and it'll work fine. If it doesn't, then the real problem will surface there.
