### ISSUE TITLE
gulp doesn't exit correctly when using gulp-nodemon and launched via npm

### ISSUE THREAD

**Issue by myndzi** [JacksonGariety/gulp-nodemon#83]
nodemon binds SIGINT to, presumably, attempt to nicely forward this to its children:
https://github.com/remy/nodemon/blob/v1.3.8/lib/monitor/run.js#L322-L324

But, if it was required, it doesn't actually exit its process:
https://github.com/remy/nodemon/blob/v1.3.8/lib/monitor/run.js#L274-L284

Instead, it emits the 'exit' event, expecting whatever required it to deal with this case. (This seems to have been a change between 1.3.7 and 1.3.8; doesn't seem like a semver "patch" change to me...)

`gulp-nodemon` doesn't bind the 'exit' handler, and so the process stays running.

Now, if you run gulp directly, since the original event handler is a `.once` event, you can press ctrl+c twice to have it exit properly. But for some reason, if you are running gulp via an npm script, you get dumped to the command line after one press. Some disconnect, I guess, between the npm script runner and its child handling.

Luckily, `gulp-nodemon` returns the nodemon object, so you can actually bind the `exit` handler yourself in your gulp script:

    var monitor = nodemon(opts...);
    monitor.on('exit', function () { process.exit(); });

This took care of the problem for me.

This functionality should *probably* be implemented in `gulp-nodemon`, but it could also be fixed in `nodemon` itself. At the very least, if no fix is forthcoming, the caveat should be documented prominently and probably featured in the example.

**Comment by myndzi** [comment]
This isn't actually quite enough since it doesn't cover restarts...

**Comment by myndzi** [comment]
This will take care of that:

    var monitor = nodemon(....);
    process.once('SIGINT', function () {
      monitor.once('exit', function () {
        process.exit();
      });
    });

**Comment by Zolmeister** [comment]
+1

**Comment by JacksonGariety** [comment]
@myndzi @Zolmeister should I still implement this, or should I simply update to nodemon 1.4?

**Comment by myndzi** [comment]
Thus daosn

**Comment by myndzi** [comment]
This doesn't appear to have been fixed, or else it has regressed. Still applies with the latest instance of nodemon / gulp-nodemon. Not hunting it down this time, just continuing to use my workaround -- but thought I'd bring it to someone's attention.

**Comment by Zolmeister** [comment]
Confirmed this is currently still happening, and appears to be simply requiring nodemon which causes the issue.

Current workaround involves not using nodemon, based on:
https://gist.github.com/webdesserts/5632955

```coffee
gulp.task 'watch:dev:server', ['dev:server'], ->
  gulp.watch paths.coffee, ['dev:server']

gulp.task 'dev:server', do ->
  devServer = null
  process.on 'exit', -> devServer?.kill()
  ->
    devServer?.kill()
    devServer = spawn 'coffee', ['bin/dev_server.coffee'], {stdio: 'inherit'}
    devServer.on 'close', (code) ->
      if code is 8
        gulp.log 'Error detected, waiting for changes'
```

**Comment by kennethklee** [comment]
Currently using this workaround:
```javascript
nodemon(...)
  .once('quit', function () {
    process.exit()
  })
```
