### ISSUE TITLE
How can I use node-inspector with gulp-nodemon ?

### ISSUE THREAD

**Issue by misterfresh** [JacksonGariety/gulp-nodemon#85]
I'm using gulp nodemon with browser-sync and it's working great.
Now I'd like to set it up so that when I write a "debugger;" statement in my code, it will open node inspector on live reload.
How can I do that?
Thanks

**Comment by JacksonGariety** [comment]
@misterfresh have you tried starting gulp-nodemon with `debug: true` as an element of the config object?

**Comment by JacksonGariety** [comment]
@misterfresh if that doesn't work, try calling nodemon directly from the console and passing the `--debug` flag. If that work than that flag needs to be added to the config.

**Comment by beebase** [comment]
fyi:
Executing 'nodemon --debug server.js'  in a terminal triggers node-inspector.
However, when adding it as an elem in the config object, node-inspector won't kick in.

![image](https://cloud.githubusercontent.com/assets/446089/9586028/a9f98ff8-501a-11e5-9cc4-4efadf78793f.png)

**Comment by goncaloneves** [comment]
I found a solution on the config object using exec parameter that works fine, even with lint task on restart event:

```javascript
/** Create debug Gulp task that runs server.js through nodemon with inspector and debug flag */
gulp.task('debug', function() {
  nodemon({
    exec: 'node-inspector && node --debug',
    ext: 'js',
    ignore: ['.idea/*', 'node_modules/*'],
    script: 'server.js',
    tasks: ['lint'],
    verbose: true
  }).on('start', ['']);
});
```

**Comment by ionutzp** [comment]
@goncaloneves the ```exec``` did the trick thanks, tried it earlier with ```execMap``` and it couldn't get it to work

**Comment by goncaloneves** [comment]
@ionutzp: for future reference, try this:
```javascript
gulp.task('debug', function() {
  nodemon({
    execMap: {
      js: 'node-inspector & node --debug'
    },
    ext: 'js',
    ignore: ['.idea/*', 'node_modules/*'],
    script: 'server.js',
    tasks: ['lint'],
    verbose: true
  }).on('start', ['']);
});
```

**Comment by cudasteve** [comment]
Wish I would have found this thread a while back.  In case it helps anyone in the future, here's an alternative solution I came up with that uses the `nodeArgs` option if you need a little more control over node-inspector or want to have it available as its own task.

    var nodeInspector = request('gulp-node-inspector');
    gulp.task('inspect', function () {
        gulp.src([]).pipe(nodeInspector({
            debugPort: 5859,
            webHost: '0.0.0.0',
            webPort: '8085',
            preload: false
        }));
    });
    gulp.task('start', (args.debug) ? ['inspect'] : null, function () {
        var options = {
            script: './server/index.js',
            nodeArgs: [],
            watch: ['./lib', './server', '!./server/public', '!./server/logs', 'gulpfile.js']
        };
        if (args.debug) {
            nodeOptions.nodeArgs.push('--debug');
        }
        nodemon(nodeOptions);
    }

At the command line, you can run `gulp start --debug` to start nodemon in debug mode and launch node-inspector.

**Comment by 360disrupt** [comment]
@cudasteve
You need to use yargs in gulp otherwise there will be nor arguments visible:
https://github.com/bcoe/yargs

Also I named òptions`to `nodeOptions ` to get it working.

**Comment by cudasteve** [comment]
@360disrupt thanks for the catches!

**Comment by jpierson** [comment]
I followed link from #92 which let me here bug neither **execMap** or **exec** seem to make any difference to me as I am still not able to get [breakpoints to hit in VSCode](https://github.com/Microsoft/vscode/issues/1552#issuecomment-167818604).

```javascript
  nodemon({
    script: 'server.js',
    ext: 'js html',
    exec: 'node --debug',
    env: {
      'NODE_ENV': 'development'
  })
```

**Comment by niftylettuce** [comment]
So how do we get `DEBUG=*` logs to show up for `nodemon({})`?  I tried `debug: true` option and `env: { 'DEBUG': '*' }` as well.

**Comment by niftylettuce** [comment]
Nevermind, I had `stdout: false` :laughing:

**Comment by love2dishtech** [comment]
When we are trying to run it using VSCode using a launch configuration, it starts the gulp task in the inspect mode, which binds it to a random port. However, when we have the --inspect in the gulp task, it binds it to a new different random port. This does not allow the VSCode to track the code. Any particular solution for this ?
