### ISSUE TITLE
call function in gulp-nodemon monitored process

### ISSUE THREAD

**Issue by jmls** [JacksonGariety/gulp-nodemon#87]
I have gulp-nodemon running a process (started with foo.js) 

When a file changes on the disk, I need to call a function in the running process - is this possible, or do I need to add a watch in the process itself ?

**Comment by JacksonGariety** [comment]
@jmls nodemon and gulp-nodemon are both going to kill your app when something changes, so calling the function itself wouldn't work very effectively or consistently.

What you want to do is use [gulp-watch](https://www.npmjs.com/package/gulp-watch) and start your app from within gulp using `child_process.fork()` and then `child.send()`.
