### ISSUE TITLE
How reload after app restart?

### ISSUE THREAD

**Issue by ngerritsen** [JacksonGariety/gulp-nodemon#88]
If I use the .on('restart', fn) on gulp nodemon, the function runs before the app has even finished restarting? I can understand this is default behaviour. Is there any way to get notified when the app is finished restarting from nodemon? I want to use it to reload my browser with browsersync.

    gulp.task('node', ['transpile-node'], function () {
        return gp.nodemon({
            script: './dist/index.js',
            watch: './src/server',
            ignore: ['*.test.js'],
            tasks: ['transpile-node']
        }).on('restart', function(){
            browserSync.reload();
        });
    });

Kind regards,

Niels

**Comment by monteirocode** [comment]
+1

**Comment by JacksonGariety** [comment]
@ngerritsen @monteirocode use the `start` event: https://github.com/remy/nodemon/blob/master/doc/events.md
