### ISSUE TITLE
passing args to node process via 'gulp nodemon'

### ISSUE THREAD

**Issue by ORESoftware** [JacksonGariety/gulp-nodemon#89]
with npm start, I can pass args to the node process like so

```npm start -- --some_flag```

in that case the some_flag flag is passed to node itself

but I am having trouble figuring out how to pass args with nodemon, and gulp nodemon in particular 

```gulp nodemon``` works great

but this doesn't work

```gulp nodemon -- --some_flag```

is this possible? thanks

**Comment by ORESoftware** [comment]
I did some more legwork

there is the ```nodeArgs``` option

but using nodeArgs of course does this:

```node --some_option ./bin/www.js```

what I am looking for is:

```node ./bin/www.js --some_option```

**Comment by ORESoftware** [comment]
guessing around did the trick

instead of the option nodeArgs, I use args like so:

```javascript
   nodemon({

        script: 'bin/www.js',
        ext: 'js',
        ignore: ['public/*','*.git/*','*.idea/*'],
        args:['--use_socket_server','--use_hot_reloader'],
        nodeArgs: [],
        env: {'NODE_ENV': 'development'}

    }).on('restart', []);
```

this results in this command line command:

```node bin/www.js --use_socket_server --use_hot_reloader```

great thanks

**Comment by vedraan** [comment]
For anyone looking to run node in strict mode the solution is to use ```nodeArgs: ['--use-strict']```, since running it in ```args``` won't work.
If you're interested in knowing why anyone would want to run node in strict mode, it's related to ES6 support: https://nodejs.org/en/docs/es6/

**Comment by JacksonGariety** [comment]
may I close this?

**Comment by ORESoftware** [comment]
yeah thanks
