### ISSUE TITLE
Problem watching file changes

### ISSUE THREAD

**Issue by pensierinmusica** [JacksonGariety/gulp-nodemon#90]
Hi,

I'm using Node v4.1.0, and `gulp-nodemon` 2.0.4, and it looks like `gulp-nodemon` is not detecting file changes in my server directory.

This is the relevant part of my configuration:

```js
var run = require('run-sequence');
var $ = require('gulp-load-plugins')();

gulp.task('default', function (cb) {
  run(
    'css',
    'server',
    ['browser', 'watch'],
    cb
  );
});

gulp.task('server', function () {
  $.nodemon({
    script: 'path/to/my/server/',
    ext: 'js json html'
  })
```

When I run `gulp`, `gulp-nodemon` starts the server fine, but then it doesn't detect any file changes and it never restarts (in case it matters, please note that the server is not in the same directory as the "gulpfile").

Instead, if I just run the standard `nodemon` from the command line in the server folder, it all works fine, it detects file changes and it restarts as expected.

Any idea what I'm doing wrong, or what is causing this issue?

Thanks!

**Comment by burkhardr** [comment]
Can you `cd node_modules/gulp-nodemon/ && npm install nodemon@1.4.1` and see if that fixes it for you?

We're currently experiencing issues with file watch in >1.4.2

**Comment by pensierinmusica** [comment]
Ok, I tried to swap it with nodemon v1.4.1 and now it crashes immediately:

```
TypeError: Cannot read property 'map' of undefined
    at /temp/app/node_modules/gulp-nodemon/node_modules/nodemon/lib/nodemon.js:138:59
    at /temp/app/node_modules/gulp-nodemon/node_modules/nodemon/lib/config/index.js:83:7
    at ready (/temp/app/node_modules/gulp-nodemon/node_modules/nodemon/lib/config/checkWatchSupport.js:28:7)
    at /temp/app/node_modules/gulp-nodemon/node_modules/nodemon/lib/config/checkWatchSupport.js:61:9
    at ChildProcess.exithandler (child_process.js:194:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
```

**Comment by adambuczynski** [comment]
I was having the same issue. Since one of the last updates, the files weren't being watched anymore, and I have to press CTRL-C twice to exit the script from the terminal.

Swapping out nodemon with 1.4.1 seemed to fix the issue and bring everything back to normal.

**Comment by adambuczynski** [comment]
Perhaps you could freeze the version of nodemon in package.json at 1.4.1 for the time being until these issues are resolved?

**Comment by burkhardr** [comment]
We did the manual step above and then froze all our project's dependencies with `npm shrinkwrap`.

nodemon 1.4.x seems to be quite a big refactor and, unfortunately, also breaks a few things.

**Comment by adambuczynski** [comment]
1.4.1 works for us it's 1.7.x that's causing the problems. I'll consider
shrink wrapping the project but preferably we'd keep the rest of the
modules updateable.

Ideally however, the problems should be fixed in this plugin I guess.

**Comment by remy** [comment]
@burkhardr the refactor was on an internal module code only, not at the entry points. Obviously something is up, but I suspect this should be simple to investigate and fix at the integration.

**Comment by remy** [comment]
To get more debug output, can you run your usual commands, but introduce the `DEBUG=nodemon,nodemon:*` environment variable, and record and paste the output here.

**Comment by adambuczynski** [comment]
Yes, I'll give it a go tomorrow

**Comment by pensierinmusica** [comment]
@adambuczynski if you check https://github.com/JacksonGariety/gulp-nodemon/issues/90#issuecomment-141459766 actually using `gulp-nodemon` with nodemon v1.4.1 is causing a crash on my side (with Node v4.1.0).

**Comment by adambuczynski** [comment]
Hmm, we must be having different issues then.

**Comment by jmls** [comment]
yeah, I just hit this problem as well. Moving back to 1.4.1 seems to have fixed the problem

**Comment by adambuczynski** [comment]
Any heads up on this problem getting fixed/addressed?

**Comment by remy** [comment]
I'm still waiting for an answer on my last comment...

**Comment by adambuczynski** [comment]
Sorry my bad, forgot all about it!

```shell
  nodemon bus new listener: reset (0) +0ms
  nodemon bus new listener: reset (0) +3ms
  nodemon bus new listener: quit (0) +15ms
  nodemon bus new listener: quit (0) +0ms
  nodemon bus new listener: restart (0) +1ms
  nodemon bus new listener: restart (0) +0ms
  nodemon bus new listener: reset (2) +7ms
  ...
  nodemon bus emit: reset +24s
  nodemon:watch resetting watchers +1ms
  nodemon reset +0ms
  nodemon bus new listener: log (0) +2ms
  nodemon bus new listener: log (0) +0ms
  nodemon config: dirs +76ms [ '/Users/Adam/Sites/clients/mka/server',
  '/Users/Adam/Sites/clients/mka/env' ]
  nodemon bus emit: log +13ms
[06:44:08] [nodemon] 1.7.1
  nodemon bus emit: log +0ms
[06:44:08] [nodemon] reading config /Users/Adam/Sites/clients/mka/nodemon.json
  nodemon bus emit: log +2ms
[06:44:08] [nodemon] to restart at any time, enter `rs`
  nodemon bus emit: log +0ms
[06:44:08] [nodemon] ignoring: /Users/Adam/Sites/clients/mka/.git/**/* /Users/Adam/Sites/clients/mka/node_modules/**/* bower_components .sass-cache /Users/Adam/Sites/clients/mka/.git/**/* /Users/Adam/Sites/clients/mka/node_modules/**/* /Users/Adam/Sites/clients/mka/client/**/* /Users/Adam/Sites/clients/mka/public/**/*
  nodemon bus emit: log +0ms
[06:44:08] [nodemon] watching: /Users/Adam/Sites/clients/mka/server/**/* /Users/Adam/Sites/clients/mka/env/**/*
  nodemon bus emit: log +0ms
[06:44:08] [nodemon] watching extensions: js,json
  nodemon bus emit: log +1ms
[06:44:08] [nodemon] starting `node server/server.js`
  nodemon spawning +0ms node server/server.js
  nodemon bus emit: log +8ms
[06:44:08] [nodemon] child pid: 25670
  nodemon bus new listener: exit (0) +2ms
  nodemon bus new listener: exit (0) +0ms
  nodemon start watch on: server,env +0ms
  nodemon start watch on: /Users/Adam/Sites/clients/mka/server, /Users/Adam/Sites/clients/mka/env +1ms
  nodemon ignore dirs regex(/\.git|node_modules|bower_components|\.sass\-cache|\.git|node_modules|client|public/) +0ms
  nodemon bus emit: log +10ms
[06:44:08] [nodemon] watching 0 files
```

Then changing a file in `server` doesn't trigger anything. Lastly, pressing ctrl-C twice is required to stop nodemon first and then gulp:

```shell
^C  nodemon bus emit: quit +3m
  nodemon bus emit: exit +25ms
^C
```

**Comment by adambuczynski** [comment]
@remy did that help, or do you need more specific information?

**Comment by jrock2004** [comment]
Having the same issue. Doing the solution above for setting nodemon to 1.4.1 fixes the issue for me

**Comment by cafesanu** [comment]
Adding `nodemom 1.4.1` to my `package.json`'devDependencies` rather than letting gulp-nodemon install it fixed it for me as well.

**Comment by simono** [comment]
@jrock2004 @cafesanu gulp-nodemon 2.0.4 actually uses nodemon 1.4.1 https://github.com/JacksonGariety/gulp-nodemon/commit/c0a22ea621bb00a2d6f03a4f676d5f8d9a71ce09

**Comment by adambuczynski** [comment]
Yes, using gulp-nodemon 2.0.4 seems to have "fixed" the issue with file watches. It still requires two cltr-C's to terminate gulp and nodemon.

**Comment by remy** [comment]
What happens when gulp-nodemon uses the latest version? 1.8.1?

**Comment by adambuczynski** [comment]
I currently have gulp-nodemon 2.0.4 and nodemon version 1.8.1, and while the file watches are working now, it still requires the two ctrl-C's to terminate both processes.

**Comment by JacksonGariety** [comment]
@remy @adambuczynski PR 8ee28a46a9f335d9babf0131fde29b646cc621c3 should fix this. Pushed it to npm this morning.

**Comment by jakeorr** [comment]
Thanks for getting it merged, @JacksonGariety. Happy to contribute!

**Comment by adambuczynski** [comment]
Excellent, thanks @JacksonGariety

**Comment by BrightShadow** [comment]
Hi, I will refresh the discussion. I have nodemon 1.14.11, gulp-nodemon 2.2.1, and I had same issue.
What fixed it for me was to add `ext: 'ts scss html json js'` to nodemon options, like this:
```
gulp.task('watch', ['build'], function () {
    return nodemon({
        script: 'index.js',
        ext: 'ts scss html json js',
        watch: ['src', './'],
        tasks: ['build']
    });
});
```

And suddenly started working. In my opinion this is a bug, watch should watch all '*' without any extention set. Such example without extensions are on gulp-nodemon github page, where I found it. 👎
