### ISSUE TITLE
Add script flags/parameters

### ISSUE THREAD

**Issue by adambuczynski** [JacksonGariety/gulp-nodemon#97]
Is it possible to add support for script flags/parameters to be passed on to nodemon?
For example, I want to run my script with the `--harmony_destructuring` flag, but get errors when I append this to the `script` property, and I couldn't find any other properties where I can pass this to in the documentation.

**Comment by stanofsky** [comment]
You can define your own default executables using [`execMap`](https://github.com/remy/nodemon/blob/master/README.md#default-executables) property.

```javascript
gulp.task('start', function () {
  nodemon({
        script: 'app.js',
        env: { 'NODE_ENV': 'development' },
        execMap: {
            js: 'node --harmony_destructuring'
        }
})
```

**Comment by adambuczynski** [comment]
Excellent, thank you
